CityAirport = {
	'Jinan': 'tna',
	'Guangzhou': 'can',
	'Baotou': 'bav',
	'Beijing': 'bjs',
	'Changchun': 'cgq',
	'Chongqing': 'ckg',
	'Chengdu': 'ctu',
	'Dalian': 'dlx',
	'Haikou': 'hak',
	'Huhehaote': 'het',
	'Hefei': 'hfe',
	'Haerbin': 'hrb',
	'Nanchang': 'khn',
	'Kunming': 'kmg',
	'Lanzhou': 'lhw',
	'Lasa': 'lxa',
	'Lianyungang': 'lyg',
	'Luoyang': 'lya',
	'Nanjing': 'nkg',
	'Nanning': 'nng',
	'Shanghai': 'sha',
	'Xian': 'sia',
	'Shenzhen': 'szx',
	'Sanya': 'syx',
	'Qingdao': 'tao',
	'Tianjin': 'tsn',
	'Taiyuan': 'tyn',
	'Wulumuqi': 'urc',
	'Wuhan': 'wuh',
	'Xiamen': 'xmn',
	'Yantai': 'ynt',
	'Zhuhai': 'zuh'
}

WeekDay = ['sun', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat']